/* version.c */
/* Autogenerated by Makefile - DO NOT EDIT */

const char *version_string = "1.13"
;
const char *compilation_string = "nacl64-gcc -DHAVE_CONFIG_H -DSYSTEM_WGETRC=\"/home/lind/tmp/lind/sdk/linux_x86/etc/wgetrc\" -DLOCALEDIR=\"/home/lind/tmp/lind/sdk/linux_x86/share/locale\" -I. -I../lib -I../lib -O3";
const char *link_string = "nacl64-gcc -O3 -lrt ftp-opie.o ../lib/libgnu.a";
